<?php
$xhtml = '
    <tr id="tr_'.$this->product['id'].'" data-id="'.$this->product['id'].'">
        <td width="100px" class="text-bold text-red text-middle">'.$this->product['code'].'</td>
        <td width="100px" class="text-middle">'.$this->product['fullName'].' </td>
        <td class="numbers"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="1" min="1"></td>
        <td class="price text-middle text-right box-price">
            <input class="form-control text-right money base_price" name="contract_product[price][]" type="text" value="'.number_format($this->product['basePrice']).'" min="0">
        </td>
        <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" readonly value="'.number_format($this->product['basePrice']).'"></td>
        <td class="hidden">
            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$this->product['id'].'">
            <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$this->product['fullName'].'">
            <input class="form-control" type="text" name="contract_product[code][]" value="'.$this->product['code'].'">
            <input class="form-control" type="text" name="contract_product[cost][]" value="'.$this->product['inventories'][0]['cost'].'"> 
            <input class="form-control" type="text" name="contract_product[weight][]" value="'.$this->product['weight'].'"> 
            <input class="form-control" type="text" name="contract_product[categoryId][]" value="'.$this->product['categoryId'].'"> 
            <input class="form-control" type="text" name="contract_product[categoryName][]" value="'.$this->product['categoryName'].'"> 
        </td>
        <td class="text-center"><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 10px 0 0 5px; font-size: 20px;"></i></td>
    </tr>';
    echo $xhtml;
?>


